name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            dist
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
            
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
        
      - name: Run tests
        run: yarn test
        
      - name: Build package
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
            echo "No cached build found, building from scratch"
            yarn build
          else
            echo "Using cached build"
          fi
        
      - name: Save build cache
        uses: actions/cache/save@v3
        with:
          path: |
            dist
          key: ${{ runner.os }}-build-${{ github.sha }}
        
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release